apiVersion: v1
kind: ConfigMap
metadata:
  name: kk-payments-config
  namespace: default
  labels:
    app.kubernetes.io/name: kk-payments
    environment: production
data:
  NODE_ENV: "production"
  DB_HOST: "production-db"
  DEFAULT_CURRENCY: "KES"
