apiVersion: v1
kind: Service
metadata:
  name: kk-payments
  labels:
    app.kubernetes.io/name: kk-payments
spec:
  selector:
    app.kubernetes.io/name: kk-payments
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
