apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: kijani-staging
  labels:
    app.kubernetes.io/name: jenkins-deployer
    app.kubernetes.io/part-of: kijanikiosk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: kijani-staging
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - services
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer
  namespace: kijani-staging
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: kijani-staging
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: kijani-production
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - services
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer
  namespace: kijani-production
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: kijani-staging
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io
